image: jaegertracing/protobuf

stages:
  - build


build:
  stage: build
  script: 
    - cmake -DCMAKE_BUILD_TYPE=Release . 
    - make -j10
  artifacts:
      paths:
        - lib/OSMPTrafficAgent.fmu

  
