image: ubuntu:20.04

before_script:
  - apt update
  - DEBIAN_FRONTEND="noninteractive" apt install -y git python3-pip python3-dev libglib2.0-dev
  - git clone https://$USER_AUTH_CODE@$OPENPASS_URL /openpass
  - pip3 install --upgrade pip
  - pip3 install -r /openpass/pyOpenPASS/requirements.txt
  - cp ikaDriverAgent.fmu /ikaDriverAgent.fmu

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  OPENPASS_URL: "gitlab.ika.rwth-aachen.de/setlevel/openpass.git"
  USER_AUTH_CODE: "geller:glpat-q8KxApwGqCAMWNaak2qW"

stages:
  - build
  - deploy

build_fmu:
  stage: build
  before_script:
  - apt update
  - DEBIAN_FRONTEND="noninteractive" apt install -y cmake build-essential git
  script: 
    - cmake -DCMAKE_BUILD_TYPE=Release .
    - make -j10
    - cp lib/ikaDriverAgent.fmu ikaDriverAgent.fmu
  artifacts:
    paths:
      - ikaDriverAgent.fmu

deploy_to_openpass:
  stage: deploy
  image: ubuntu:20.04
  script: 
    - "curl -X POST --fail -F token=eea9e0095f33e1c72b9e32c6eb390a -F ref=master https://gitlab.ika.rwth-aachen.de/api/v4/projects/1469/trigger/pipeline"
  rules: 
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH" # run job on master branch