


variables:
  GIT_SUBMODULE_STRATEGY: recursive
before_script:
  - apt update
  - DEBIAN_FRONTEND="noninteractive" apt install -y cmake build-essential #git
  - apt install -y libprotobuf-dev protobuf-compiler
  #- git submodule sync --recursive
  #- git submodule update --init --recursive

buildFMU1804:
  image: ubuntu:18.04
  stage: build
  script: 
    - cmake . 
    - make -j10
  artifacts:
      paths:
        - lib/ikaDriverAgent.fmu

buildFMU2004:
  image: ubuntu:20.04
  stage: build
  script: 
    - cmake . 
    - make -j10
  artifacts:
      paths:
        - lib/ikaDriverAgent.fmu

buildFMUmingw:
  image: mmozeiko/mingw-w64
  stage: build
  script: 
    - cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release .
    - mingw32-make.exe -j7
  artifacts:
      paths:
        - lib/ikaDriverAgent.fmu
  

