image: ubuntu:20.04

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  OPENPASS_URL: "gitlab.ika.rwth-aachen.de/setlevel/openpass.git"
  USER_AUTH_CODE: "geller:glpat-q8KxApwGqCAMWNaak2qW"

stages:
  - build
  - test
  - deploy

before_script:
  - apt update
  - DEBIAN_FRONTEND="noninteractive" apt install -y cmake build-essential git
  - git clone https://$USER_AUTH_CODE@$OPENPASS_URL /openPASS
  - apt install -y libglib2.0-dev python3-pip python3-dev
  - pip3 install --upgrade pip
  - pip3 install -r /openPASS/pyOpenPASS/requirements.txt

build_fmu:
  stage: build
  script: 
    - cmake -DCMAKE_BUILD_TYPE=Release .
    - make -j10
    - cp lib/ikaDriverAgent.fmu /ikaDriverAgent.fmu

test_generic:
  stage: test
  script:
    - cd /openPASS/pyOpenPASS
    - >-
      python3 ./main.py 
      -s /openPASS 
      -r /openPASS/test 
      -c /openPASS/test/end_to_end.json 
      --scope generic

test_velocity:
  stage: test
  script:
    - cd /openPASS/pyOpenPASS
    - >-
      python3 ./main.py 
      -s /openPASS 
      -r /openPASS/test 
      -c /openPASS/test/end_to_end.json 
      --scope velocity

test_reachend:
  stage: test
  script:
    - cd /openPASS/pyOpenPASS
    - >-
      python3 ./main.py 
      -s /openPASS 
      -r /openPASS/test 
      -c /openPASS/test/end_to_end.json 
      --scope reachend

test_toffset:
  stage: test
  script:
    - cd /openPASS/pyOpenPASS
    - >-
      python3 ./main.py 
      -s /openPASS 
      -r /openPASS/test 
      -c /openPASS/test/end_to_end.json 
      --scope toffset

deploy_to_artifacts:
  stage: deploy
  script:
    - mv lib/ikaDriverAgent.fmu ikaDriverAgent.fmu
  artifacts:
      paths:
        - ikaDriverAgent.fmu
  rules: 
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH" # run job on master branch
    
deploy_to_openpass:
  stage: deploy
  dependencies: 
  - deploy_to_artifacts
  script: 
    - "curl -X POST --fail -F token=eea9e0095f33e1c72b9e32c6eb390a -F ref=master https://gitlab.ika.rwth-aachen.de/api/v4/projects/1469/trigger/pipeline"
  rules: 
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH" # run job on master branch